### ISSUE TITLE
permission for commit request

### ISSUE THREAD

**Issue by rajsameer** [vertica/vertica-grafana-datasource-.2.0#9]
Hi ,

I want to add support of variable repeating in grafana Vertica data source. I tried to push a local branch and it seems i do not have permission. Can you please point me the process of contribution.

Thanks
Sameer

**Comment by rajsameer** [comment]
Also, can we bump the go driver version in this project? I am currently testing the latest released go driver with this data source.

Sameer

**Comment by huebnerr** [comment]
Hi Rajsameer,

Please fork the driver into your own github area, commit, and submit a PR from there. Once built and verified, we can pull it into main and then submit the newest release to Grafana.

I've recently committed a branch that updates the vertica-sql-go driver to v0.2.1 and will be merging it in very soon once I've had a chance to sanity check everything.

Thanks!
